name: actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      uses: main/checkout@v3
      run: |
        npm install
        npm run test
