name: actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
  steps:
    uses: main/checkout@v3
    name: unit tests
    run: |
      npm install
      npm run test
